export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECK_OUT = 'CHECK_OUT'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const EMPTY_CART = 'EMPTY_CART'
